@startuml
'https://plantuml.com/class-diagram

skinparam class {
BackgroundColor LightGrey
ArrowColor Black
BorderColor Black
BackgroundColor<<Foo>> DarkGrey
}
skinparam classAttributeIconSize 0
skinparam backgroundcolor Gray
skinparam stereotypeCBackgroundColor YellowGreen

class MainApp {
-spel : ChuckALuckSpel
+main() : void
}

class ChuckALuckSpel {
-dobbelbeker : Dobbelbeker
-ronde : int
-saldo : int
-geluksGetal : int
-aantalWinnendeWorpen : int
+werpGeldIn(int bedrag) : void
+betaalUit() : void
+speelRonde(int geluksgetal, int inzet) : void
+toString() : String
}

class Dobbelbeker {
-aantalKeerGeluksGetalGeworpen : int
-dobbelstenen : Dobbelsteen[]
+toString() : String
}

class DobbelSteen {
-getal : int
-werpDobbelsteen() : void
+isGetalGelijkAanGeluksGetal : boolean
+toString() : String
}

MainApp -right-> "1" ChuckALuckSpel : spel
ChuckALuckSpel -down-> "1" Dobbelbeker : beker
Dobbelbeker -left-> "3" DobbelSteen : dobbelstenen

@enduml